name: Deploy Blazor WebAssembly to GitHub Pages

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish .NET project
      run: dotnet publish -c Release -o build

    - name: Fix base href for GitHub Pages
      run: |
        sed -i 's|<base href="/" />|<base href="/ReadSlovnik/" />|' build/wwwroot/index.html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/wwwroot

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
